#!/bin/bash
echo "K3S CLUSTER SETUP CHEAT SHEET"
echo "--------------------------------"

echo "STEP 1: ON NODE-01 (CONTROL PLANE)"
echo "Run this to install K3s:"
echo "  curl -sfL https://get.k3s.io | sh -"
echo ""
echo "Run this to give Bogdan admin access:"
echo "  mkdir -p ~/.kube"
echo "  sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config"
echo "  sudo chown bogdan:bogdan ~/.kube/config"
echo "  echo 'export KUBECONFIG=~/.kube/config' >> ~/.bashrc"
echo "  export KUBECONFIG=~/.kube/config"
echo ""
echo "Run this to extract the secret token for Node-02:"
echo "  sudo cat /var/lib/rancher/k3s/server/node-token"
echo "--------------------------------"

echo "STEP 2: ON NODE-02 (WORKER NODE)"
echo "Run this FIRST to fix the hostname duplicate issue:"
echo "  sudo hostnamectl set-hostname node-02"
echo "  sudo sed -i 's/ubuntu/node-02/g' /etc/hosts"
echo ""
echo "Run this to join the cluster (replace <TOKEN> with the token from Step 1):"
echo "  curl -sfL https://get.k3s.io | K3S_URL=https://192.168.122.153:6443 K3S_TOKEN=<TOKEN> sh -"
